### ISSUE TITLE
I have a question about data generation

### ISSUE THREAD

**Issue by lk1048453160** [longrongyang/LNCIS#2]
what are the annotation path p_a and p_g? How to generate them?
thanks!

**Comment by longrongyang** [comment]
In this work, the noise on class labels is generated by artificially corrupting object class labels, which is similar with existing works in label-noise learning. The annotation path p_a is the path of original annotations and the annotation path p_g is the path of generated noisy annotations in your own computer. For example, p_a and p_g can be set to "/data/LNCIS/instances_train2017.json" and "/data/LNCIS/new_instances_train2017.json" respectively.

**Comment by lk1048453160** [comment]
what I understand is that, the p_a is a json file has all train annotation path. 
Content of the document is just like this:
'annotations':
/home/Data-Cityscapes/gtFine_trainvaltest/gtFine/train/aachen_000000_000019_gtFine_polygons.json
/home/Data-Cityscapes/gtFine_trainvaltest/gtFine/train/aachen_000001_000019_gtFine_polygons.json
...
Is that correct?
thanks~

**Comment by longrongyang** [comment]
You need generate an annotation file that contain annotation information of all images rather than a json file that contains paths of all annotations. You can find the code in github easily (For example, the project **mmdetection**, et al.). The project also contains codes for this in [cityscapes.py](https://github.com/longrongyang/LNCIS/blob/master/tools/convert_datasets/cityscapes.py).

**Comment by lk1048453160** [comment]
I will try it. thansk!
